import './global.css';
import Navbar from "./components/navbar/Navbar"
export const metadata = {
  title: 'Welcome to graphql-next',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
     <Navbar>
        {children}
      </Navbar>
        </body>
    </html>
  );
}
